token: "YOUR_LICHESS_BOT_TOKEN_HERE"  # Get this from https://lichess.org/account/oauth/token

url: "https://lichess.org/"

engine:
  dir: "/root/fluxfish-nnue"
  name: "fluxfish.sh"
  protocol: "uci"
  working_dir: "/root/fluxfish-nnue"
  
  uci_options:
    Threads: 1

  # Time management
  move_overhead: 500  # Milliseconds to reserve for network latency

challenge:
  concurrency: 1  # Number of games to play at once
  
  # Accept challenges from anyone
  sort_by: "best"
  accept_bot: true
  accept_human: true
  
  # Time controls to accept (in minutes)
  max_increment: 180
  min_increment: 0
  max_base: 315360000  # Accept any time control
  min_base: 0
  
  # Game modes
  variants:
    - standard
  time_controls:
    - bullet
    - blitz  
    - rapid
    - classical
    - correspondence
  modes:
    - casual
    - rated

# Greeting messages
greeting:
  hello: "Hi! I'm FluxFish, a custom NNUE chess engine. Good luck!"
  goodbye: "Good game! Thanks for playing."

# Abort games if opponent doesn't move
abort_time: 30

# Logging
logging:
  enable: true
  verbose: false
